fix: zero value is returned without a unit at size/rem transform
amzn/style-dictionary pull request #1302
Opened 2024-08-12 05:26 UTC by yinm

_Issue #, if available:_
#1267

_Description of changes:_
As the title says,  I fixed that zero value is returned without a unit at size/rem transform.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-12 09:15 UTC, jorenbroekema requested changes

2024-08-12 09:15 UTC, jorenbroekema commented on lib/common/transforms.js
> +      if (parsedVal === 0) return '0';
```suggestion
      if (parsedVal === 0) return Number.isInteger(nonParsed) ? 0 : '0';
```

Let's check that if the token value is the number 0, we leave it as a number. Please add a test for this as well :)

2024-08-12 10:27 UTC, jorenbroekema approved these changes

2024-08-12 10:28 UTC, jorenbroekema commented
Awesome, thanks for contributing a fix! Just waiting for @dbanksdesign to approve and look to release it

2024-08-13 04:00 UTC, dbanksdesign approved these changes

2024-08-13 04:00 UTC, merged