chore: upgrade to eslint v9 and migrates flatconfig
amzn/style-dictionary pull request #1386
Opened 2024-11-09 18:17 UTC by aliesenli

**Description of changes:**

This PR upgrades ESLint to version 9 and [migrates to the new flat-config format](https://eslint.org/docs/latest/extend/plugin-migration-flat-config), which has been the default configuration format since ESLint v9.0.0. 

The `.eslintrc.json` file has been removed in favor of the new `eslint.config.js` file.

Following packages has been adjusted to make this migration possible:
```json
"@typescript-eslint/parser": "^8.13.0",  --> added parser to recognize react files (built in)

"eslint": "^8.7.0",                      --> upgrade to "^9.14.0",
"eslint-config-react-app": "^7.0.1",     --> swapped with "eslint-plugin-react": "^7.37.2",
"eslint-plugin-mocha": "^10.2.0",        --> upgrade to "^10.5.0",
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-09 18:21 UTC, aliesenli commented on eslint.config.js
> +delete GLOBALS_BROWSER_FIX['AudioWorkletGlobalScope '];
Apparently following little bug has not been fixed and the `browser globals` is throwing an error without removing the extra trailing space: https://github.com/sindresorhus/globals/pull/184

2024-11-09 20:02 UTC, aliesenli commented on eslint.config.js
> +        ...GLOBALS_BROWSER_FIX,
Our dependency `@babel/plugin-transform-private-property-in-object` relies on a version of `globals` where the `AudioWorkletGlobalScope` property in `globals.browser` contains an extra trailing space, causing a linting error.

As a temporary fix, I addressed this by removing the extra space (GLOBALS_BROWSER_FIX).

Alternatively, we could consider overriding the globals package in `package.json`:

```json
"overrides": {
  "globals": "^15.12.0"
}
```

2024-11-12 09:33 UTC, jorenbroekema requested changes
Thanks for the PR, I migrated a bunch of repos to ESLint v9 recently and contemplated doing it for Style Dictionary but couldn't find the time for it, so this is much appreciated.

Just 1 suggestion for patching globals@11 version

2024-11-12 18:38 UTC, aliesenli commented
> Thanks for the PR, I migrated a bunch of repos to ESLint v9 recently and contemplated doing it for Style Dictionary but couldn't find the time for it, so this is much appreciated.
> 
> Just 1 suggestion for patching globals@11 version

Thanks for the suggestion! I've just patched the globals@11 and rebased onto main.

2024-11-13 13:23 UTC, jorenbroekema approved these changes

2024-11-13 13:24 UTC, jorenbroekema commented
I think the package-lock version gets out of sync quite a bit because during the version bump the package-lock would have to be synced by doing an npm install after the bump in package.json and committing that with the version bump, I guess our release orchestration (changesets) isn't doing this. It's not a problem imo but could be solved by doing npm install after rebasing on latest main and committing the pkg lock version bump. Not a blocker for me though

2024-11-18 17:02 UTC, dbanksdesign approved these changes

2024-11-19 09:46 UTC, merged