fixed typo
amzn/style-dictionary pull request #690
Opened 2021-08-31 10:57 UTC by lukasoppermann

2021-08-31 23:04 UTC, chazzmoney approved these changes

2021-09-02 22:42 UTC, dbanksdesign requested changes
Thanks for catching this! This file is actually being generated from JSDoc, so if you could update the JSDoc comment here: https://github.com/amzn/style-dictionary/blob/main/lib/common/formats.js#L644 first and then run `npm run generate-docs` that should make sure this change doesn't get thrown out when we generate the docs in the future. Thanks!

2021-09-03 09:50 UTC, lukasoppermann commented
Hey @dbanksdesign I changed it according to your comment, hope this is correct. Cheers

2021-09-03 16:17 UTC, dbanksdesign approved these changes
LGTM! :shipit:

2021-09-07 22:40 UTC, merged