Ignore docs and examples from the published npm package
amzn/style-dictionary pull request #915
Opened 2023-01-10 16:28 UTC by brettimus

*Issue #, if available:* Closes https://github.com/amzn/style-dictionary/issues/914

*Description of changes:*

This PR changes the `.npmignore` to exclude files related to examples and documentation from the published NPM package. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-07 14:28 UTC, tripu approved these changes
Static analysis tools looking for vulnerabilities are finding a file `style-dictionary/examples/advanced/custom-file-header/node_modules/json5/package.json` and screaming [CVE-2022-46175](https://nvd.nist.gov/vuln/detail/CVE-2022-46175).

Yet another reason to exclude examples from the npm tarball.

So, +10 from my and my colleagues.

2023-03-08 02:50 UTC, coliff approved these changes

2023-03-16 22:10 UTC, dbanksdesign approved these changes
LGTM! Thank you for this!

2023-03-16 22:12 UTC, chazzmoney commented
Unfortunately, the SD executable expects the examples folder to be present. However, you could remove / hide the advanced folder. Or, you could suggest a PR to remove the init functionality.

2023-03-16 22:13 UTC, dbanksdesign commented
Ah good catch @chazzmoney! You are right, this would break `style-dictionary init` .

2023-03-16 22:15 UTC, chazzmoney commented
For clarity, this is the code that would be broken:

https://github.com/amzn/style-dictionary/blob/main/bin/style-dictionary#L60-L67

so if you retain examples/basic and examples/complete and npmignore examples/advanced, it would remove that vulnerability.

Or, maybe we could be convinced to remove the init...

2023-03-16 22:16 UTC, chazzmoney requested changes

2023-03-16 22:16 UTC, chazzmoney commented on .npmignore
> +examples/
See the comments on the PR. Can't exclude this folder directly because it breaks functionality. Other options would work though.

2024-03-27 00:36 UTC, jorenbroekema commented
Revamping docs, examples in the near future, will try to ensure if we still put them on NPM, they at least don't have security issues, but will close this particular PR as it would break init command

2024-03-27 00:36 UTC, closed without merging

2024-03-27 08:35 UTC, brettimus commented
Sorry I never followed up on this PR! But yeah, I think for teams who need to be meticulous about every dependency and sub-dependency they use, having minimal deps for the examples would be much appreciated. Will be happy to see #914 closed 🙏